In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
np.__version__

'1.18.1'

In [4]:
np.dtype

numpy.dtype

In [5]:
np.shape

<function numpy.shape(a)>

In [6]:
a.shape

(4,)

In [7]:
x=np.array([21,22,23,24,25,26])
x

array([21, 22, 23, 24, 25, 26])

In [8]:
x.shape

(6,)

In [9]:
x.ndim

1

In [10]:
np.dtype

numpy.dtype

In [11]:
x.size

6

In [12]:
x.dtype

dtype('int32')

In [13]:
type(x)

numpy.ndarray

In [14]:
data=np.array([[1,2,3],[4,5,6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
data.ndim

2

In [16]:
data.size

6

In [17]:
data.shape

(2, 3)

In [18]:
data.dtype

dtype('int32')

In [19]:
data2=np.array([[7,8,9],[10,11,12]])
print(data2)

[[ 7  8  9]
 [10 11 12]]


In [20]:
data

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
data2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [22]:
y=np.concatenate([data,data2])
y

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
data

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
data2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [25]:
np.add(data,data2)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [26]:
np.multiply(data,data2)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [27]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
a.shape

(3, 4)

In [29]:
b=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
b.shape

(4, 3)

In [31]:
b.size

12

In [32]:
b.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
b.min()

1

In [34]:
b.max()

12

In [35]:
b.mean()

6.5

In [36]:
b.dtype

dtype('int32')

In [40]:
b.itemsize

4

In [38]:
data

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
data.itemsize

4

In [41]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [42]:
a.data

In [45]:
z=np.arange(25)
print(z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [46]:
s=z.reshape(5,5)
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [47]:
s.shape

(5, 5)

In [48]:
s.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
print(s.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [51]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [53]:
np.ones((3,3),dtype='int')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [54]:
np.ones((2,3,4), dtype='int')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [55]:
np.ones((2,3,4), dtype='float')

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [56]:
np.ones((2,3,4), dtype='bool')

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [57]:
np.empty((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [58]:
np.empty((5,4))

array([[1.02681725e-311, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000],
       [7.56587583e-307, 5.30276956e+180, 1.57076922e-076,
        4.57576052e-071],
       [4.86371561e-086, 3.35709102e-143, 6.01433264e+175,
        6.93885958e+218],
       [5.56218858e+180, 3.94356143e+180, 4.30160087e+174,
        1.03123122e-071],
       [2.80065148e-032, 4.08961829e-037, 5.88890739e-144,
        1.50008929e+248]])

In [62]:
p=np.arange(1,13).reshape(4,3)
p

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [65]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [66]:
a=np.array([10,20,30,40])
a

array([10, 20, 30, 40])

In [67]:
b=np.arange(4)

In [68]:
b

array([0, 1, 2, 3])

In [69]:
a
b

array([0, 1, 2, 3])

In [70]:
print(a)
print(b)

[10 20 30 40]
[0 1 2 3]


In [71]:
c=a-b
c

array([10, 19, 28, 37])

In [72]:
b=np.random.random((2,3))

In [73]:
b

array([[0.72485442, 0.45838349, 0.06355439],
       [0.01090023, 0.82484698, 0.6279773 ]])

In [74]:
c

array([10, 19, 28, 37])

In [75]:
np.sqrt(c)

array([3.16227766, 4.35889894, 5.29150262, 6.08276253])

In [76]:
np.exp(c)

array([2.20264658e+04, 1.78482301e+08, 1.44625706e+12, 1.17191424e+16])