In [1]:
# import libraries
import pandas as pd # for data manupulation or analysis
import numpy as np # for numeric calculation
import matplotlib.pyplot as plt # for data visualization
import seaborn as sns # for data visualization

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC

In [3]:
df=pd.read_csv("D:\\DATA-TRAINED\\dataset1-master\\dataset1-master\\winedataset.csv")
df.head()

Class  Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  \
0      1    14.23        1.71  2.43               15.6        127   
1      1    13.20        1.78  2.14               11.2        100   
2      1    13.16        2.36  2.67               18.6        101   
3      1    14.37        1.95  2.50               16.8        113   
4      1    13.24        2.59  2.87               21.0        118   

   Total phenols  Flavanoids  Nonflavanoid phenols  Proanthocyanins  \
0           2.80        3.06                  0.28             2.29   
1           2.65        2.76                  0.26             1.28   
2           2.80        3.24                  0.30             2.81   
3           3.85        3.49                  0.24             2.18   
4           2.80        2.69                  0.39             1.82   

   Color intensity   Hue  diluted wines  Proline      
0             5.64  1.04           3.92         1065  
1             4.38  1.05           3.40         1050  
2             5.68  1.03           3.17         1185  
3             7.80  0.86           3.45         1480  
4             4.32  1.04           2.93          735

In [4]:
x=df.drop('Class',axis=1)

In [5]:
y=df['Class']

In [6]:
x.shape

(178, 13)

In [7]:
y.shape

(178,)

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=50)

In [9]:
print('shape of x_train:',x_train.shape)
print('shape of x_test:',x_test.shape)
print('shape of y_train:',y_train.shape)
print('shape of y_test:',y_test.shape)

shape of x_train: (142, 13)
shape of x_test: (36, 13)
shape of y_train: (142,)
shape of y_test: (36,)


In [10]:
df.shape

(178, 14)

In [11]:
x_train

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
81     12.72        1.81  2.20               18.8         86           2.20   
160    12.36        3.83  2.38               21.0         88           2.30   
16     14.30        1.92  2.72               20.0        120           2.80   
57     13.29        1.97  2.68               16.8        102           3.00   
123    13.05        5.80  2.13               21.5         86           2.62   
..       ...         ...   ...                ...        ...            ...   
132    12.81        2.31  2.40               24.0         98           1.15   
33     13.76        1.53  2.70               19.5        132           2.95   
109    11.61        1.35  2.70               20.0         94           2.74   
139    12.84        2.96  2.61               24.0        101           2.32   
176    13.17        2.59  2.37               20.0        120           1.65   

     Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
81         2.53                  0.26             1.77             3.90  1.16   
160        0.92                  0.50             1.04             7.65  0.56   
16         3.14                  0.33             1.97             6.20  1.07   
57         3.23                  0.31             1.66             6.00  1.07   
123        2.65                  0.30             2.01             2.60  0.73   
..          ...                   ...              ...              ...   ...   
132        1.09                  0.27             0.83             5.70  0.66   
33         2.74                  0.50             1.35             5.40  1.25   
109        2.92                  0.29             2.49             2.65  0.96   
139        0.60                  0.53             0.81             4.92  0.89   
176        0.68                  0.53             1.46             9.30  0.60   

     diluted wines  Proline      
81            3.14          714  
160           1.58          520  
16            2.65         1280  
57            2.84         1270  
123           3.10          380  
..             ...          ...  
132           1.36          560  
33            3.00         1235  
109           3.26          680  
139           2.15          590  
176           1.62          840  

[142 rows x 13 columns]

In [12]:
x_test

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
117    12.42        1.61  2.19               22.5        108           2.00   
90     12.08        1.83  2.32               18.5         81           1.60   
80     12.00        0.92  2.00               19.0         86           2.42   
141    13.36        2.56  2.35               20.0         89           1.40   
143    13.62        4.95  2.35               20.0         92           2.00   
135    12.60        2.46  2.20               18.5         94           1.62   
122    12.42        4.43  2.73               26.5        102           2.20   
118    12.77        3.43  1.98               16.0         80           1.63   
24     13.50        1.81  2.61               20.0         96           2.53   
167    12.82        3.37  2.30               19.5         88           1.48   
40     13.56        1.71  2.31               16.2        117           3.15   
25     13.05        2.05  3.22               25.0        124           2.63   
119    12.00        3.43  2.00               19.0         87           2.00   
12     13.75        1.73  2.41               16.0         89           2.60   
63     12.37        1.13  2.16               19.0         87           3.50   
146    13.88        5.04  2.23               20.0         80           0.98   
114    12.08        1.39  2.50               22.5         84           2.56   
159    13.48        1.67  2.64               22.5         89           2.60   
100    12.08        2.08  1.70               17.5         97           2.23   
54     13.74        1.67  2.25               16.4        118           2.60   
23     12.85        1.60  2.52               17.8         95           2.48   
126    12.43        1.53  2.29               21.5         86           2.74   
38     13.07        1.50  2.10               15.5         98           2.40   
153    13.23        3.30  2.28               18.5         98           1.80   
34     13.51        1.80  2.65               19.0        110           2.35   
20     14.06        1.63  2.28               16.0        126           3.00   
103    11.82        1.72  1.88               19.5         86           2.50   
73     12.99        1.67  2.60               30.0        139           3.30   
39     14.22        3.99  2.51               13.2        128           3.00   
127    11.79        2.13  2.78               28.5         92           2.13   
48     14.10        2.02  2.40               18.8        103           2.75   
8      14.83        1.64  2.17               14.0         97           2.80   
168    13.58        2.58  2.69               24.5        105           1.55   
155    13.17        5.19  2.32               22.0         93           1.74   
13     14.75        1.73  2.39               11.4         91           3.10   
125    12.07        2.16  2.17               21.0         85           2.60   

     Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
117        2.09                  0.34             1.61             2.06  1.06   
90         1.50                  0.52             1.64             2.40  1.08   
80         2.26                  0.30             1.43             2.50  1.38   
141        0.50                  0.37             0.64             5.60  0.70   
143        0.80                  0.47             1.02             4.40  0.91   
135        0.66                  0.63             0.94             7.10  0.73   
122        2.13                  0.43             1.71             2.08  0.92   
118        1.25                  0.43             0.83             3.40  0.70   
24         2.61                  0.28             1.66             3.52  1.12   
167        0.66                  0.40             0.97            10.26  0.72   
40         3.29                  0.34             2.34             6.13  0.95   
25         2.68                  0.47             1.92             3.58  1.13   
119        1.64             

In [13]:
y_train

81     2
160    3
16     1
57     1
123    2
      ..
132    3
33     1
109    2
139    3
176    3
Name: Class, Length: 142, dtype: int64

In [14]:
y_test

117    2
90     2
80     2
141    3
143    3
135    3
122    2
118    2
24     1
167    3
40     1
25     1
119    2
12     1
63     2
146    3
114    2
159    3
100    2
54     1
23     1
126    2
38     1
153    3
34     1
20     1
103    2
73     2
39     1
127    2
48     1
8      1
168    3
155    3
13     1
125    2
Name: Class, dtype: int64

In [15]:
model=[DecisionTreeClassifier(),SVC(),KNeighborsClassifier(),MultinomialNB()]


for m in model:
    m.fit(x_train,y_train)
    m.score(x_train,y_train)
    predm=m.predict(x_test)
    print('Accuracy score of',m,'is:')
    print(accuracy_score(y_test,predm))
    print(confusion_matrix(y_test,predm))
    print(classification_report(y_test,predm))
    print('\n')

Accuracy score of DecisionTreeClassifier() is:
0.9444444444444444
[[11  2  0]
 [ 0 14  0]
 [ 0  0  9]]
              precision    recall  f1-score   support

           1       1.00      0.85      0.92        13
           2       0.88      1.00      0.93        14
           3       1.00      1.00      1.00         9

    accuracy                           0.94        36
   macro avg       0.96      0.95      0.95        36
weighted avg       0.95      0.94      0.94        36



Accuracy score of SVC() is:
0.6111111111111112
[[ 9  4  0]
 [ 1 13  0]
 [ 0  9  0]]
              precision    recall  f1-score   support

           1       0.90      0.69      0.78        13
           2       0.50      0.93      0.65        14
           3       0.00      0.00      0.00         9

    accuracy                           0.61        36
   macro avg       0.47      0.54      0.48        36
weighted avg       0.52      0.61      0.54        36



Accuracy score of KNeighborsClassifier() is:
0.

C:\Users\sagar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train_sc = sc.fit_transform(x_train)
x_test_sc = sc.transform(x_test)

In [17]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

# Suppor vector Classifier

In [18]:
# Support vector classifier
from sklearn.svm import SVC
svc_classifier = SVC()
svc_classifier.fit(x_train, y_train)
y_predm_scv = svc_classifier.predict(x_test)
accuracy_score(y_test, y_predm_scv)

0.6111111111111112

In [19]:
# Train with Standard scaled Data
svc_classifier2 = SVC()
svc_classifier2.fit(x_train_sc, y_train)
y_predm_svc_sc = svc_classifier2.predict(x_test_sc)
accuracy_score(y_test, y_predm_svc_sc)

1.0

# Logistic Regression

In [20]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
lr_classifier = LogisticRegression(random_state = 51, penalty = 'l2')
lr_classifier.fit(x_train, y_train)
y_predm_lr = lr_classifier.predict(x_test)
accuracy_score(y_test, y_predm_lr)

C:\Users\sagar\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:764: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9444444444444444

In [21]:
# Train with Standard scaled Data
lr_classifier2 = LogisticRegression(random_state = 51, penalty = 'l2')
lr_classifier2.fit(x_train_sc, y_train)
y_pred_lr_sc = lr_classifier.predict(x_test_sc)
accuracy_score(y_test, y_pred_lr_sc)

0.6111111111111112

# K – Nearest Neighbor Classifier

In [22]:

from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
knn_classifier.fit(x_train, y_train)
y_predm_knn = knn_classifier.predict(x_test)
accuracy_score(y_test, y_predm_knn)

0.6666666666666666

In [23]:
# Train with Standard scaled Data
knn_classifier2 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
knn_classifier2.fit(x_train_sc, y_train)
y_predm_knn_sc = knn_classifier.predict(x_test_sc)
accuracy_score(y_test, y_predm_knn_sc)

0.3888888888888889

# Naive Bayes Classifier

In [24]:
# Naive Bayes Classifier
from sklearn.naive_bayes import GaussianNB
nb_classifier = GaussianNB()
nb_classifier.fit(x_train, y_train)
y_predm_nb = nb_classifier.predict(x_test)
accuracy_score(y_test, y_predm_nb)

0.9722222222222222

In [25]:
# Train with Standard scaled Data
nb_classifier2 = GaussianNB()
nb_classifier2.fit(x_train_sc, y_train)
y_predm_nb_sc = nb_classifier2.predict(x_test_sc)
accuracy_score(y_test, y_predm_nb_sc)

0.9722222222222222

# Decision Tree Classifier

In [26]:
# Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
dt_classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 51)
dt_classifier.fit(x_train, y_train)
y_predm_dt = dt_classifier.predict(x_test)
accuracy_score(y_test, y_predm_dt)

0.9166666666666666

In [27]:
# Train with Standard scaled Data
dt_classifier2 = DecisionTreeClassifier(criterion = 'entropy', random_state = 51)
dt_classifier2.fit(x_train_sc, y_train)
y_predm_dt_sc = dt_classifier.predict(x_test_sc)
accuracy_score(y_test, y_predm_dt_sc)

0.3611111111111111